### PR TITLE
Pull request groupings 364

### PR DESCRIPTION
**Pull request by zakgilbert**
exclude multiple members is a go

### CODE REVIEW

**Comment by fduckart** [comment]
I don't think those git comments match our style conventions, eh.

**Comment by zakgilbert** [comment]
The commit messages or my branch names, or both?

**Comment by fduckart** [comment]
The messages. I'm not sure if we have a convention for the branch naming.

**Comment by zakgilbert** [comment]
my bad I'll go over the conventions again

**Comment by mhodgesatuh** [comment]
FYI, we have conventions for branch naming and for comments documented in
bwiki.

 - Michael

**Comment by zakgilbert** [comment]
my bad I'll go over the conventions again

**Pull request merged**
