### PR TITLE
Refactor Membership /type class and create ManagePersonResults /groupings class

### PR DESCRIPTION
**Pull request by mikhail-shkaralevich**
# Ticket Link

[GROUPINGS-1636](https://uhawaii.atlassian.net/browse/GROUPINGS-1636)

# List of squashed commits

- Refactor Membership /type class and create ManagePersonResults /groupings class.
- Fix bugs on Admin Page's Manage Person tab.
- Get rid of unused variables in the MembershipResult class.
- Write tests.
- Clean up

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Comment by mikhail-shkaralevich** [comment]
I get the error when running the integration tests. Maybe related to this [issue](https://uhawaii.atlassian.net/browse/GROUPINGS-1657).

`[ERROR] edu.hawaii.its.api.service.TestSubjectService.isValidIdentifier
[ERROR]   Run 1: TestSubjectService.isValidIdentifier:49 » NullPointer Cannot invoke "edu.hawaii.its.api.wrapper.SubjectsResults.getSubjects()" because "subjectsResults" is null`

**Review by JorWo — COMMENTED** [review]
There seems to be some Codacy issues.

**Comment by JorWo** [comment]
> I get the error when running the integration tests. Maybe related to this [issue](https://uhawaii.atlassian.net/browse/GROUPINGS-1657).
> 
> `[ERROR] edu.hawaii.its.api.service.TestSubjectService.isValidIdentifier [ERROR] Run 1: TestSubjectService.isValidIdentifier:49 » NullPointer Cannot invoke "edu.hawaii.its.api.wrapper.SubjectsResults.getSubjects()" because "subjectsResults" is null`

Please make a ticket to investigate this or include the fix in your PR, thanks!

**Comment by mikhail-shkaralevich** [comment]
> > I get the error when running the integration tests. Maybe related to this [issue](https://uhawaii.atlassian.net/browse/GROUPINGS-1657).
> > `[ERROR] edu.hawaii.its.api.service.TestSubjectService.isValidIdentifier [ERROR] Run 1: TestSubjectService.isValidIdentifier:49 » NullPointer Cannot invoke "edu.hawaii.its.api.wrapper.SubjectsResults.getSubjects()" because "subjectsResults" is null`
> 
> Please make a ticket to investigate this or include the fix in your PR, thanks!

The integration test also fails in the main branch, here's a [ticket for it.](https://uhawaii.atlassian.net/browse/GROUPINGS-1659)

**Comment by mikhail-shkaralevich** [comment]
> > > I get the error when running the integration tests. Maybe related to this [issue](https://uhawaii.atlassian.net/browse/GROUPINGS-1657).
> > > `[ERROR] edu.hawaii.its.api.service.TestSubjectService.isValidIdentifier [ERROR] Run 1: TestSubjectService.isValidIdentifier:49 » NullPointer Cannot invoke "edu.hawaii.its.api.wrapper.SubjectsResults.getSubjects()" because "subjectsResults" is null`
> > 
> > 
> > Please make a ticket to investigate this or include the fix in your PR, thanks!
> 
> The integration test also fails in the main branch, here's a [ticket for it.](https://uhawaii.atlassian.net/browse/GROUPINGS-1659)

I found the bug and fixed it. I will put the fix under this pr as a second commit.

**Comment by mikhail-shkaralevich** [comment]
> There seems to be some Codacy issues.

Fixed

**Review by JorWo — APPROVED** [review]
Looks great!

**Review by mhodgesatuh — APPROVED** [review]

**Pull request merged**
