### PR TITLE
Update spring-boot's version

### PR DESCRIPTION
**Pull request by mikhail-shkaralevich**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1727)

# List of squashed commits

- Update spring-boot's version

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Review by JorWo — APPROVED** [review]
Looks good!

**Comment by mikhail-shkaralevich** [comment]
Hold on this PR, I need to update more dependencies. Thank you

**Comment by mikhail-shkaralevich** [comment]
After consultation with Frank, I came to a conclusion that we are safe to proceed with just updating the spring-boot starter's version. The PR can be merged.

**Review by JorWo — APPROVED** [review]
Thanks for double-checking for any issues that may occur.

**Pull request merged**
