### PR TITLE
Fixes missing .mvn folder

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-1166](https://www.hawaii.edu/jira/browse/GROUPINGS-1166)

# List of squashed commits

- Fixes missing .mvn folder

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
i see an empty file in there the mvnw. Is that necessary to run our wrapper?

**Comment by fduckart** [comment]
The mvnw file does not appear to be empty. Not entirely sure why github is saying that. Maybe something about it being a script and its associated file permissions... I dunno. Also, not sure why Codacy is whining, either. I tried out mvnw and it works fine on my machine. Give it a try on yours, and if it works, I say merge this PR.

**Comment by devgav** [comment]
@fduckart. Looks like it works i guess github might have some issues detecting the script. Hopefully it doesn't show up as an empty file when we merge it.

**Review by devgav — APPROVED** [review]

**Comment by devgav** [comment]
> The mvnw file does not appear to be empty. Not entirely sure why github is saying that. Maybe something about it being a script and its associated file permissions... I dunno. Also, not sure why Codacy is whining, either. I tried out mvnw and it works fine on my machine. Give it a try on yours, and if it works, I say merge this PR.

that particular codacy issue about the delta and def not running. We discussed in a meeting that those would be fine to ignore since it's something with our codacy config for this dev-2-2-0 branch, although i don't we pinpointed where in the config it was causing this error.

**Pull request merged**
