### PR TITLE
Clean isOwner

### PR DESCRIPTION
**Pull request by miraabela**

### CODE REVIEW

**Review by zakgilbert — APPROVED** [review]

**Review by mhodgesatuh — COMMENTED** [review]
Do we need the logger line.  Seems noisy.

**Comment by fduckart** [comment]
I think this would be perfect if we had some tests added to go alone with it.

**Comment by fduckart** [comment]
Let's close this one without merging it in.

**Comment by devgav** [comment]
Closing this ticket as it is an old ticket with a member who is no longer on the team.

**Pull request closed without merging**
