### PR TITLE
Dev jarrenys 1450 Removes unused @Profile(localTest)

### PR DESCRIPTION
**Pull request by jarrenseson**
[# Ticket Link](https://uhawaii.atlassian.net/jira/software/c/projects/GROUPINGS/boards/18?modal=detail&selectedIssue=GROUPINGS-1450&assignee=6352ef57e14026a7397ea425)
Removes unused @Profile(localTest)

[1450](https://uhawaii.atlassian.net/jira/software/c/projects/GROUPINGS/boards/18?modal=detail&selectedIssue=GROUPINGS-1450&assignee=6352ef57e14026a7397ea425)

# List of squashed commits

- Deletes @Profile(localHost)
- Deletes @Profile(localTest) from GroupAttributesTest.java
- Removes changes from unused HTML documentation files
- Deletes @ActiveProfiles("localTest") from GroupTest.java

# Test Checklist

- [ X ] Unit Tests Passed:
- [ X ] Integration Tests Passed:
- [ X ] General Visual Inspection:

### CODE REVIEW

**Comment by JorWo** [comment]
Those HTML files you modified are very outdated documentation files, so you can discard the changes to them. I found that you can also remove the @`ActiveProfiles("localTest")` from GroupTest.java. Also don't forget to squash all your commits into one.

**Comment by jarrenseson** [comment]
Hey Jordan. Just letting you know that I updated everything according to your comments.

**Comment by JorWo** [comment]
You will need to squash your 7 commits into 1. It might be easier to make a new branch and move all your changes onto that one. Send me a message on Slack if you need any help.

**Review by mhodgesatuh — COMMENTED** [review]
<pre>@Profile(value={"default","dev", "localTest})  missing a closing qote

**Review by mhodgesatuh — COMMENTED** [review]
@Profile(value={"default","dev", "localTest"}) why a new space after just the last comma?

**Pull request closed without merging**
