### PR TITLE
Normalizes the properties files between the api and ui

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[GROUPINGS-1272](https://uhawaii.atlassian.net/browse/GROUPINGS-1272)

#List of squashed commits
- Adds newline to end of files

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Comment by JorWo** [comment]
Could get rid of those end of file no newline warnings?

**Review by JorWo — APPROVED** [review]
Thanks for reorganizing the properties files.

**Comment by JorWo** [comment]
Are the integration tests failing related to the fixes in this PR: https://github.com/uhawaii-system-its-ti-iam/uh-groupings-api/pull/404 ?

**Comment by Kristyn-Mimura** [comment]
Sorry, the integration tests were failing because I hadn't properly updated the new api password. It passed once I did

**Pull request merged**
