### PR TITLE
Export to CSV Button in MultiAdd members modal doesn't work-GROUPINGS-922

### PR DESCRIPTION
**Pull request by zakgilbert**
Check for null uid.
[GROUPINGS-922](https://www.hawaii.edu/jira/browse/GROUPINGS-922)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
looks clean

**Comment by zakgilbert** [comment]
Going to merge this once the lead approves the PR, though the ticket will stay open since the original issue is not resolved.
Also will create a second PR for 2.2 for the changes above.

**Comment by mhodgesatuh** [comment]
I added the Branch Managers to the list of reviewers.

**Comment by ruizaj** [comment]
Everything looks good to me, you can go ahead to do the merge

**Pull request merged**
