### PR TITLE
Re-added thymeleaf dependency and added test

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1337)

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I'm surprised thymeleaf is needed on the API.  Is there a reasonable strategy to ensure it is not needed?

**Comment by JorWo** [comment]
Just to be sure, what is the purpose of adding Thymeleaf to the API?

**Comment by carolwong492** [comment]
Frank mentioned that Thymeleaf was being used in one of the test pages.

**Comment by fduckart** [comment]
Looks great, thanks a ton.

**Pull request merged**
