### PR TITLE
Implement wrapper for Gc/Ws GroupSave

### PR DESCRIPTION
**Pull request by zakgilbert**
# Ticket Link

[GROUPINGS-1375](https://uhawaii.atlassian.net/browse/GROUPINGS-1375)

# List of squashed commits
- Implement GroupSaveCommand, GroupSaveResults, TestGroupSaveCommand, and GroupSaveResultsTest.
- Implement GorupingsUpdateDescriptionResult.java.
- Integrate new updateDescription into working code.
- Added unit testing coverage to wrapper classes.

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by zakgilbert** [comment]
Ws/Gc GroupSave lets us update the description.

**Comment by zakgilbert** [comment]
Also there is quite a bit of code coverage added in this PR.

**Review by mhodgesatuh — COMMENTED** [review]
Recommend that this first be reviewed at a team meeting this week.

**Review by mhodgesatuh — APPROVED** [review]
GroupingsUpdateDescriptionResult.java seems to be very restrictive in scope.  I'd expect a GroupingsUpdateResult class, for example, that would have a description method.  Might be one to consult with Frank to be sure we are driving down to too fine a detail.

**Pull request merged**
