### PR TITLE
Fix missing timestamp update

### PR DESCRIPTION
**Pull request by yertsti**
# Ticket Link

[1500](https://uhawaii.atlassian.net/browse/GROUPINGS-1500)

# List of squashed commits

- Fix missing timestamp update

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
A quick fix for v2.3 is fine since we need production patched ASAP,  but might want to work with Frank to look for a better coding strategy.  Be sure the fix matches the forward-60 seconds requirement evidenced in https://uhawaii.atlassian.net/browse/GROUPINGS-1491.

**Comment by JorWo** [comment]
This PR says it is going into the main branch. Did you mean to merge into devrc-2-3-0?

**Comment by fduckart** [comment]
Roger that. Can we have another Jira to refactor it? Everything about it now looks unorthodox.

**Comment by mhodgesatuh** [comment]
For the record, ticket 1500 is for production, so devrc-2-3-0 branch needs the fix ASAP.

**Comment by yertsti** [comment]
The fix is just quick and dirty and I have no idea how we would test it.

 The builder for updating the timestamp can take multiple groups and it will return an array of WsAssignAttributeResults. Right now the wrapper that holds the results from the command assumes it only gets one result back, so I think if I change everything to a list then we should be able to work for multiple group paths. 

Another way is to pass in a list of group paths to the initial update method and just execute the UpdateTimestampCommand for each path in the list. This way would probably take less work to refactor it.

**Review by JorWo — APPROVED** [review]
The dirty fix is fine for now. I would refactor it by modifying the addOwners and removeOwners function in UpdateMembershipService rather than in UpdateTimestampService

**Comment by JorWo** [comment]
If I were to make your current code more readable, I would utilize the GroupPathService and move around the if statements:
```
@Autowired
    private GroupPathService groupPathService;

    public static final Log logger = LogFactory.getLog(MembershipService.class);

    public GroupingsTimestampResult update(GroupingsResult groupingResult) {
        if (groupingResult.getResultCode().equals("SUCCESS")) {
            if (groupPathService.isOwnersGroupPath(groupingResult.getGroupPath())) {
                updateLastModifiedTimestamp(groupPathService.getGroupingPath(groupingResult.getGroupPath()));
            }
            return updateLastModifiedTimestamp(groupingResult.getGroupPath());
        }

        return new GroupingsTimestampResult();
    }
```

**Pull request merged**
