### PR TITLE
GROUPINGS-694-Create a class for global variables

### PR DESCRIPTION
**Pull request by zakgilbert**
[GROUPINGS-694](https://www.hawaii.edu/jira/browse/GROUPINGS-694)

### CODE REVIEW

**Comment by zakgilbert** [comment]
Not all the values from the properties are implemented. This pull request is to make sure that formating and implementation are acceptable before finishing the class.

**Review by fduckart — COMMENTED** [review]
Looks like a bunch of other updates are in here for some reason. Not sure that's a good idea.

**Comment by zakgilbert** [comment]
I'm just removing a few unused variables and stuff. These classes are a mess. Or do you mean the commits at the top?

**Comment by fduckart** [comment]
Pull request shows 23 files updated. Unless I'm reading that incorrectly

**Comment by zakgilbert** [comment]
There's a lot of files that use the @Value annotation to pull data from the properties files, doesn't that mean that all those files need to be refactored to use GrouperConfiguration instead?

**Comment by fduckart** [comment]
Sure looks there's other, non-related stuff in this pull, too. Also, it might be safer if you started off with submitting just the configuration class and its related test class. Just the two classes.

**Comment by zakgilbert** [comment]
If you are talking about the first few commits, those showed up cause I mistakenly branched off from my previous ticket. I ran a rebase with master and everything seems to be in order so far.

**Comment by Kobeyarai808** [comment]
Outdated and would need major refactoring to implement.

**Pull request closed without merging**
