### PR TITLE
Project Security: Change the properties files and the tests to use te…

### PR DESCRIPTION
**Pull request by zakgilbert**
…iers.

# Ticket Link

[GROUPINGS-1216](https://uhawaii.atlassian.net/browse/GROUPINGS-1216)

# List of squashed commits

- Update application-integrationTest.properties with new test identifiers.
- Update grouper.test.properties with new test identifiers.

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Looks like a start rather than a conclusion regarding changing out all test data for the officially sanctioned data.  A start is fine place to start.

**Comment by zakgilbert** [comment]
> Looks like a start rather than a conclusion regarding changing out all test data for the officially sanctioned data. A start is fine place to start.

**Comment by zakgilbert** [comment]
> Looks like a start rather than a conclusion regarding changing out all test data for the officially sanctioned data. A start is fine place to start.

Definitely a starting point, I was thinking of incrementally(through various tasks) trickling the new test users into code base as I teach @KaileeHung and @carolwong492 about the API.

**Comment by mhodgesatuh** [comment]
Sounds like a very good plan.  Thanks!

**Pull request merged**
