### PR TITLE
Updates PasswordScanner and adds its tests

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[GROUPINGS-836](https://www.hawaii.edu/jira/browse/GROUPINGS-836)

# List of squashed commits

- Adds PasswordFoundAnalyzer, PasswordFoundException, and PatternFoundException
- Deletes checkForPwd in SpringBootWebApplication and edits grouper.client.properties
- Adds pattern-property-checker test resources
- Adds PasswordScanner and PatternPropertyChecker
- Adds PasswordScannerTest and PatternPropertyCheckerTest
- Removes unused imports and Codacy error

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by fduckart — APPROVED** [review]
Looks great.

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Review by devgav — COMMENTED** [review]
i see that @KaileeHung also has a similar pr. If I merge this one would it be fine to close the other as well?

**Comment by devgav** [comment]
just got a confirmation from Carol that these changes are independent of the ones on the UI.

**Review by devgav — APPROVED** [review]

**Pull request merged**
