### PR TITLE
UpdateLastModified API call appears to be significantly delayed

### PR DESCRIPTION
**Pull request by zakgilbert**
# Ticket Link

[GROUPINGS-1295](https://uhawaii.atlassian.net/browse/GROUPINGS-1295)

# List of squashed commits
- Set last-modified:yyyymmddThhmm on grouping include and/or exclude subgroups.
- Set the timestamp one minute into the future.
- Add logger info to add/remove functions.

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by zakgilbert** [comment]
Fixing codacy errors rn.

**Review by mhodgesatuh — COMMENTED** [review]
Given that we have logger output in UpdateTimestampResult, do we need the new logger statements in production?

**Review by devgav — APPROVED** [review]
Thanks for finding such a quick fix to this issue. Ik we have have had trouble with the timestamp in the past before as well.

**Review by mhodgesatuh — APPROVED** [review]

**Comment by mhodgesatuh** [comment]
For v2.3 we should also have system testing code coverage that ensures the contract to update timestamps for changes to include and exclude lists is fully implemented.

**Comment by mhodgesatuh** [comment]
Julio's recommendation: If the UI allows for more than one person to be sent to those two methods, then you definitely want to set the timestamp after looping through the users.  The timestamp is currently set within the loop.  Zak, can you review and consider making the change as recommended if it makes sense.  It's not clear to me that having the timestamp after the loop will ensure that everything changed gets an updated timestamp though, but then I don't fully understand the code at this point.

**Pull request merged**
