### PR TITLE
Changes TestGroupAttributeService and TestMemberAttributeService

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1336)

# List of squashed commits

- Tried fixing groupAttributeAssignsTest
- Fixed groupAttributeAssignsTest
- Standardizes naming in tests

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Food for thought.  You might need to have the test ensure it gets back enough identities randomly.  If someone else where to install the app and manage to get it to run, they might not have enough data to generate enough test identities, in which case the test should fail with a suitable message.

**Review by JorWo — APPROVED** [review]
Looks great,

**Review by zakgilbert — APPROVED** [review]

**Comment by JorWo** [comment]
Could you rebase this branch and let me know if all tests still pass? Thanks.

**Comment by JorWo** [comment]
> Could you rebase this branch and let me know if all tests still pass? Thanks.

Confirmed with Carol and Kailee the tests still pass.

**Pull request merged**
