### PR TITLE
clean up application-localhost.properties file

### PR DESCRIPTION
**Pull request by FeimeiChen**
# Ticket Link

[Ticket 1478](https://uhawaii.atlassian.net/browse/GROUPINGS-1478)

# List of squashed commits

- Commit 1:clean up application-localhost.properties file (API)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by FeimeiChen** [comment]
Could I change the content on the UI side under this same Ticket 1478? 

- change to spring.config.activate.on-profile=localhost
- and remove the CSV

**Comment by mhodgesatuh** [comment]
@FeimeiChen yes.  as the current ticket owner you have this discretion.

**Comment by FeimeiChen** [comment]
> @FeimeiChen yes. as the current ticket owner you have this discretion. So I won't review it since you might be doing more work on this ticket.

get it, thank you

**Review by JorWo — APPROVED** [review]
Looks good.

**Pull request merged**
