### PR TITLE
Export to CSV Button in MultiAdd members modal doesn't work.

### PR DESCRIPTION
**Pull request by zakgilbert**
Check for null uid in remove and add member functions, if null then retrieve.
[GROUPINGS-922](https://www.hawaii.edu/jira/browse/GROUPINGS-922).

### CODE REVIEW

**Comment by zakgilbert** [comment]
Note that this is not a completed ticket, but these changes are needed asap. Another pull request will be open once the modal is fixed.

**Comment by mhodgesatuh** [comment]
Looks good

**Comment by mhodgesatuh** [comment]
And we need to backport the fix to 2.2 I assume.

**Comment by ruizaj** [comment]
I'll commit this one in, looks fine to me.

**Pull request merged**
