### PR TITLE
Added descriptions to groupPath and memberships classes. Added wrapper for WsFindGroupsResults.

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[Groupings-533](https://www.hawaii.edu/jira/browse/GROUPINGS-533)

# List of squashed commits

- Changed makePaths in HelperServiceImpl to use parallel streams
- Added description to constructors, getters, and setters of groupPath and membership type classes
- Added description testing for MembershipTest and GroupingPathTest
- Changed optInPaths in GroupingAssignmentServiceImpl to use parallel streams
- Updated HelperServiceTest to include a MockBean of GrouperApiService
- Added FindGroupsResults, Results, updated SubjectResults, and created tests with 100% coverage for them

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by devgav — APPROVED** [review]

**Comment by fduckart** [comment]
Looks good overall, but we need some more tweaks, I think. Can you add the newlines at the ends of files where they are missing. There also seems to be something odd going on... there's a bunch of places where multiple calls are made to create the same data transfer object.. that can't be ideal. Also, can you give the new testing property key names some kind of prefix/name so that they are logically grouped together.

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Comment by devgav** [comment]
I believe that we are still waiting for UI changes to go along with this issue.

**Comment by devgav** [comment]
@JorWo gave me approval to close this pr while he continues working on a UI solution to be coupled with the API changes

**Pull request closed without merging**
