### PR TITLE
Rename TestGrouperApiService to TestGrouperApiServiceTutorial, add more implementations to tests

### PR DESCRIPTION
**Pull request by lukepag**
# Ticket Link

https://www.hawaii.edu/jira/browse/GROUPINGS-1057

# List of squashed commits

-Added to groupAttributeDefNamesTest()
-Added to groupAttributeAssignsTest()
-Finished hasMemberResultsTest
-Added more to groupsOfTest
-Finalized attributeAssignsTest
-Finalized groupsOfTest
-Added to and finalized groupAttributeDefNamesTest
-Added to and finalized groupAttributeAssignsTest
-Finalized hasMemberResultsTest
-Finalized assignAttributesResultsTest
-Finalized assignAttributesResultsForGroupTest
-Finalized grouperPrivilegesLiteResultTest
-Finalized membersResultsTest
-Finalized subjectsResultsTest
-Finalized findGroupsResultsTest and assignAttributeValueTest/added stemLookupTest
-New imports used for testing
-Rename file to TestGrouperApiServiceTutorial
-Added disclaimer to top of file
-Fix rebase conflicts
-Delete unused imports and private fields
-Refactor subjectLookupTest

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
There are codacy issues to be addressed.

**Review by devgav — APPROVED** [review]
These changes seem fine to merge. Seems like a good way for newer members to mess around/get more familiar with testing

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.  This tutorial class is a great idea, but where in Getting Started do we plan to reference it?  Otherwise it's more like a Easter egg waiting to be discovered.

**Comment by lukepag** [comment]
> I don't see any issues. This tutorial class is a great idea, but where in Getting Started do we plan to reference it? Otherwise it's more like a Easter egg waiting to be discovered.

Maybe under learning resources or testing? Learning resources may be better since this file is meant to be a learning resource and not for testing

**Pull request merged**
