### PR TITLE
Create a Failure Analyzer for a grouper credential failure

### PR DESCRIPTION
**Pull request by gitCarrot**
# Ticket Link

[ Ticket-791 ](https://uhawaii.atlassian.net/browse/GROUPINGS-791)

# List of squashed commits
- Add test for CredentialFailure Analyzer and Exception
- Change the superclass of exception to CredentialException

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Codacy reports: MINOR Code Style
Unused import - javax.security.auth.login.CredentialException.
import javax.security.auth.login.CredentialException;

**Comment by JorWo** [comment]
Could you explain how this works? It looks like it is missing code to actually check if the credentials for Grouper are invalid.

**Comment by gitCarrot** [comment]
> Could you explain how this works? It looks like it is missing code to actually check if the credentials for Grouper are invalid.

Based on the other failure analyzer, the purpose of Failure Analyzer for credential is not the code to actually check if the credentials for Grouper are invalid. It returns a FailureAnalysis object containing the description of the problem, the recommended action, and the underlying cause after getting the exception.

**Comment by JorWo** [comment]
> > Could you explain how this works? It looks like it is missing code to actually check if the credentials for Grouper are invalid.
> 
> Based on the other failure analyzer, the purpose of Failure Analyzer for credential is not the code to actually check if the credentials for Grouper are invalid. It returns a FailureAnalysis object containing the description of the problem, the recommended action, and the underlying cause after getting the exception.

I see. but I would like to see a way to actually check that the Grouper credentials are invalid.

**Pull request closed without merging**
