### PR TITLE
getMemberships API call in 2.1.1 not returning properly-GROUPINGS-865

### PR DESCRIPTION
**Pull request by zakgilbert**
[GROUPINGS-865](https://www.hawaii.edu/jira/browse/GROUPINGS-865)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Overall looks ok IFAICT, but some of the comments are not up to our standards, such as:

**Comment by mhodgesatuh** [comment]
Overall looks ok IFAICT, but some of the comments are not up to our standards, such as:

        //get rid of duplicates
vs
        // Get rid of duplicates.


If we need to keep commented out code, should provide inline comments to explain why, because we generally don't:
        //        for (int i = 0; i < 6; i++) {
        //            membershipService.deleteGroupMemberByUsername(ownerUsername, GROUPING_INCLUDE, username[i]);
        //        }

**Comment by fduckart** [comment]
Those two new tests in the GroupingAssignmentServiceTest class... I'm not exactly sure what the bottom part of each one is suppose to prove.

**Comment by fduckart** [comment]
In MembershipServiceTest#getMembershipResultsTest ... that try/catch exception test needs a fail call in the middle so you can make sure the error is happening.

**Comment by zakgilbert** [comment]
For your first comment you are talking about these right 
@Test
    public void getOptOutGroupsTest() {
        List<String> optOutPaths =
                groupingAssignmentService.getOptOutGroups(users.get(0).getUsername(), users.get(1).getUsername());
        assertNotNull(optOutPaths);
        Set<String> pathMap = new HashSet<>();
        for (String path : optOutPaths) {
            assertTrue(pathMap.add(path));
        }
    }

    @Test
    public void getOptInGroupsTest() {
        List<String> optInPaths =
                groupingAssignmentService.getOptInGroups(users.get(0).getUsername(), users.get(1).getUsername());
        assertNotNull(optInPaths);
        Set<String> pathMap = new HashSet<>();
        for (String path : optInPaths) {
            assertTrue(pathMap.add(path));
        }
    }

**Pull request merged**
