### PR TITLE
API Overrides file no longer needs the project-base.dir

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1139](https://www.hawaii.edu/jira/browse/GROUPINGS-1139)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
It would be nice if I could also have some mac users check if this new overrides file runs the project on their machines as well. It has worked on my windows machine and my linux VM

**Review by zakgilbert — APPROVED** [review]

**Comment by mhodgesatuh** [comment]
Kailee and Carol are mac uses;  mentors, perhaps you could help them test gavin's branch on their macs and update this PR?

**Comment by devgav** [comment]
> Kailee and Carol are mac uses; mentors, perhaps you could help them test gavin's branch on their macs and update this PR?

I'll ask them and update this pr appropriately if we find anything that doesn't work

**Comment by devgav** [comment]
update: Just asked Kailee to try and run the project with the new API overrides file and it seems like the project runs fine with these new changes on MAC

**Comment by devgav** [comment]
Fix below mispelling

**Comment by fduckart** [comment]
It'd be great if you could get that one Windows line-ending out of there. Also, can you put a new-line after the very last entry.

**Review by fduckart — APPROVED** [review]
Great

**Pull request merged**
