### PR TITLE
Fix autowiring error for GrouperService

### PR DESCRIPTION
**Pull request by lukepag**
# Ticket Link

[1775] https://uhawaii.atlassian.net/browse/GROUPINGS-1775

# List of squashed commits

- Fix autowiring error for GrouperService
- Add new unit test for grouperApiService

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Do we need new unit tests for this?

**Comment by lukepag** [comment]
> Do we need new unit tests for this?

I just realized that the grouperApiService function didn't originally have a unit test in OotbGrouperPropertyConfigurer. I can make a new one

**Comment by JorWo** [comment]
Is this PR ready for review? I noticed you marked this PR as a draft.

**Comment by lukepag** [comment]
> Is this PR ready for review? I noticed you marked this PR as a draft.

Sorry, forgot to change it back. It's ready now though!

**Review by JorWo — APPROVED** [review]

**Review by JorWo — APPROVED** [review]
Thanks for writing the unit and integration tests!

**Pull request merged**
