### PR TITLE
Refactored enable/disable preference endpoints in GroupingsRestController and GroupAttributeService

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[Groupings-1053](https://www.hawaii.edu/jira/browse/GROUPINGS-1053)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by devgav — APPROVED** [review]
These changes seem fine. Thanks for removing some of the if else logic we had in our endpoints

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.  Very glad to see that test are included.

**Comment by fduckart** [comment]
Sorry, was paying attention to this PR. Not sure I really like the changes here. Seems like we got cleaner controller calls in exchange for messier service calls. Would it be possible to keep going with this work?

**Comment by devgav** [comment]
> 

I can message Jordan to push another ticket to continue his work for this ticket to clean up the service calls.

**Pull request merged**
