### PR TITLE
Implement try...when and add comment stating scanner is closed at end of try

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1149](https://uhawaii.atlassian.net/browse/GROUPINGS-1149)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
I thought we agreed to leave the code as is because it is working and to just add an inline comment to clarify that the try block closes the resource.  Or was that a different conversation?

**Comment by devgav** [comment]
> I thought we agreed to leave the code as is because it is working and to just add an inline comment to clarify that the try block closes the resource. Or was that a different conversation?

This pr adds the inline comment inside above the try..when

**Review by mhodgesatuh — APPROVED** [review]
Thanks for adding the inline comment

**Comment by fduckart** [comment]
This reminds of all the signs people put up in the ITC building telling us stuff that's already obvious... LOL. I still wish we could track down what is going on. I suspect there's probably a real bug somewhere, but we need to suss it out, if it's there. I'll look at the code today if I get a chance.

**Pull request merged**
