### PR TITLE
remove unnecessary activeProfile localTest

### PR DESCRIPTION
**Pull request by Rubegen**
# Ticket Link

[Ticket](Insert Link Here)

# List of squashed commits

- Commit 1
- Commit 2
- Commit 3

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
There are no checks on the checklist above, so Gaven doesn't know if you've went through it successfully.

**Comment by devgav** [comment]
We should be careful that removing these ActiveProfiles don't 

1. influence any .properties files
2. the beans loaded into the application context

i believe we use these ActiveProfiles to control the variables we have in our .properties file in src/main/resources

**Review by fduckart — COMMENTED** [review]
Awesome!

**Review by devgav — APPROVED** [review]
I checked these files with the master API branch and seems like we don't use any of our variables from our .properties files. I can approve this message and go ahead and merge it thanks for  removing unnesscary code.

**Pull request merged**
