### PR TITLE
Bumped up spring version to 5.3.18

### PR DESCRIPTION
**Pull request by buccatm**
# Ticket Link

[GROUPINGS-1105](https://www.hawaii.edu/jira/browse/GROUPINGS-1105)

# List of squashed commits

Only 1 commit

# Test Checklist

- [ ] Unit Tests Passed:
- [ ] Integration Tests Passed:
- [ ] General Visual Inspection:

### CODE REVIEW

**Comment by fduckart** [comment]
So, did we give up on this task or something?

**Comment by mhodgesatuh** [comment]
Marcos had this one and is away for the summer.  We'll have to reassign it
to get traction.  I'll add this to the agenda for this week's team meetings.

**Comment by devgav** [comment]
I am going to close this ticket for now as it has gone stale. I have assigned the ticket to myself and hopefully get it pushed sometime today if there are no troubles

**Comment by mhodgesatuh** [comment]
Thanks for taking over the ticket.

**Pull request closed without merging**
