### PR TITLE
Removes unecessary dependencies in the pom file

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-1222](https://uhawaii.atlassian.net/browse/GROUPINGS-1222)

# List of squashed commits

- Removes unused dependencies

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Normally commenting out code is not recommended, but it works in this case.

**Comment by fduckart** [comment]
Just delete this stuff since we can get it back from the git history if we need it. Although... one thing I discovered since we talked about this stuff at the last meeting is a wiki page showing the app's URL for swagger (http://localhost:8081/uhgroupingsapi/swagger-ui.html), so I guess we need to make sure this is still working after removing the possible junk in the pom.

**Review by mhodgesatuh — APPROVED** [review]
Looks good, thanks

**Review by devgav — APPROVED** [review]

**Comment by devgav** [comment]
Added myself and @zakgilbert to this pr as well.

**Pull request merged**
