### PR TITLE
GROUPINGS-871 - add getGroupingOwners() and isSoleOwner()

### PR DESCRIPTION
**Pull request by chakhon**
# Ticket Link

[GROUPINGS-871](https://www.hawaii.edu/jira/browse/GROUPINGS-871)

# List of squashed commits

- add getGroupingOwners() and isSoleOwner()

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Passing in the many of null parameters doesn't smell right.  Let's go over this with Frank during the code walkthrough.

grouperApiService.membersResults(
                SUBJECT_ATTRIBUTE_NAME_UID,
                lookup,
                path,
                null,
                null,
                null,
                null);

**Review by Kobeyarai808 — APPROVED** [review]
I'm aware of Michael's comment, I do not see any issues with this code and I approve this pull request. Although I like these changes, please talk with Michael and Frank, I can merge it in once we are all on the same page. Please DM me when a resolution is made.

**Comment by chakhon** [comment]
After discussion in meeting, Michael suggested that I should experiment with method overloading before merging this pull request. I will reopen this pull request once I have look into if method overloading can address the concern.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good!

**Pull request merged**
