### PR TITLE
Provide test coverage for type/Grouping.java

### PR DESCRIPTION
**Pull request by zakgilbert**
# Ticket Link

[GROUPINGS-1318](https://uhawaii.atlassian.net/browse/GROUPINGS-1318)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
setName seems vague.  Could the variable name make it clear what the context is for this name?

**Comment by JorWo** [comment]
> setName seems vague. Could the variable name make it clear what the context is for this name?

I think setName is clear, it is setting the name of the grouping.

**Review by JorWo — APPROVED** [review]

**Comment by mhodgesatuh** [comment]
setGroupingName is clear I would say, based on the description you
provided.  Often when describing something, selection of a clear name
becomes more obvious.

Michael Hodges
Middleware, Identity and Access Management
University of Hawaii, Information Technology Services
***@***.***
808-956-7195 (GMT -10:00)

we>$

**Comment by mhodgesatuh** [comment]
However, it occurs to me that there may be a case where setName is not
vague and maybe that's in play here.
grouping = new Grouping (attributes here)
grouping->setName(new grouping name here)

**Comment by zakgilbert** [comment]
image
Now at full coverage. Realized during my meeting presentation what was wrong.

**Pull request merged**
