### PR TITLE
Adjust endpoints to match new API bible documentation.

### PR DESCRIPTION
**Pull request by zakgilbert**
**Commits**
- Rename endpoint 'syncDestinations' to 'sync-destinations'.
- Rename endpoint "/groupings/{uid}/memberships" to "/groupings/members/{uid}/memberships".
- Rename endpoint '/groupings/optInGroups/ {uid}' to '/groupings/members/{uid}/opt-in-groups'.
- Rename 'usersToAdd' to 'uids'.
- Rename 'usersToRemove' to 'uids'.
- Rename 'resetGroup' to 'reset-group'.
- Rename "/groupings/{path}/syncDests/{syncDestName}/disable" to  "/groupings/{path}/sync-destination/{id}/disable".
- Rename "/groupings/{path}/syncDests/{syncDestName}/enable" to  "/groupings/{path}/sync-destination/{id}/enable".
- Rename "/groupings/{path}/preferences/{prefenceId}/disable" to  "/groupings/{path}/preference/{id}/disable".
- Rename "/groupings/{path}/preferences/{preferenceId}/enable" to  "/groupings/{path}/preference/{id}/enable".
- Rename 'includeMembers' to 'include-membeers'.
- Rename 'excludeMembers' to 'exclude-members'.
- Rename 'uidToCheck' to 'uid'.
- Rename '/{path:[\\w-:.]+}/owners/{uid}' to  '/groupings/{path:[\\w-:.]+}/owners/{uid}'.
- Rename 'adminsGroupings' to 'admins-and-groupings'.
- Provide unit coverage for *isSoleOwner()* endpoint.
- Provide coverage for *isSoleOwner()* in integrations.
---
[GROUPINGS-1118](https://www.hawaii.edu/jira/browse/GROUPINGS-1118)

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
There seem to be some codacy issues which are mostly removing unused import statements.

**Review by devgav — APPROVED** [review]
These changes look fine to me.

**Comment by fduckart** [comment]
I don't think dashes in URIs are a good idea.

**Comment by zakgilbert** [comment]
> I don't think dashes in URIs are a good idea.

Are you sure? It's all over the RESTful API documentation.
https://restfulapi.net/resource-naming/

**Pull request merged**
