### PR TITLE
Remove warnings and unused imports

### PR DESCRIPTION
**Pull request by William-Liang808**
[Groupings - 996](https://www.hawaii.edu/jira/browse/GROUPINGS-996)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Merged before addressing the unused imports?

**Comment by Kobeyarai808** [comment]
The unused imports have been removed. I didn't see anything suspicious.

**Comment by Kobeyarai808** [comment]
I ran the unit tests and integration tests are running as we speak. Will told me he ran them but I am double-checking.

**Comment by Kobeyarai808** [comment]
Integration test just finished with no errors.

**Pull request merged**
