### PR TITLE
Upgrade to Java 17 and Spring Boot 3

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[GROUPINGS-824](https://uhawaii.atlassian.net/browse/GROUPINGS-824)

# List of squashed commits

- Update GitHub workflow
- Fix failing tests
- Add comments to remove the line after we upgrade to Grouper 4

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Before you merge this PR I need to stop the current test API environment from getting automatically updated by Jenkins since 17 is not supported, so let's coordinate.  I will also need to coordinate a CNAME change to engage the new Test API VM.  When you are ready, DM me so we can coordinate.  
Great work!

**Comment by mhodgesatuh** [comment]
I meant to ask. This PR also updates the project to Spring Boot 3?

**Comment by JorWo** [comment]
> I meant to ask. This PR also updates the project to Spring Boot 3?

Yes it does!

**Comment by fduckart** [comment]
Awesome!

**Pull request merged**
