### PR TITLE
Fixes getNumberOfMemberships and its test

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-1262](https://uhawaii.atlassian.net/browse/GROUPINGS-1262)

# List of squashed commits

- Fixes getNumberOfMemberships and its test
- Finalizes additions to getNumberOfMembershipsTest
- Optimizes getNumberOfMemberships
- Optimizes numberOfGroupings
- Fixes missing EOL

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Very nice to also see the corresponding unit test.

**Comment by fduckart** [comment]
This is anal, but can you update the comment to use a leading upper-case letter and a period at the end. And can you format the comment so that it doesn't go past the 80 column marker? Just make it a two-line comment, if necessary.

I'm thinking it would be super cool if we have a custom Predicate for that filter. Not sure if it should be a static helper method or a custom class altogether, but it should have a nice name telling us what it does.

Lastly... I think it would be great if we took this further... maybe a thinner method to count the memberships. The current method creates whole structures of data, then just ignores it all just to get the count. A new, thinner method could perhaps return the integer we want it to be, too, maybe.

**Review by devgav — COMMENTED** [review]
This looks fine just make the changes regarding Frank's comment 👍.

**Comment by devgav** [comment]
Can you fix that missing EOL as well.

**Review by devgav — APPROVED** [review]
Looks great. I spoke with Kailee and said she was going to work on another ticket regarding Frank's suggestions.

**Pull request merged**
