### PR TITLE
Overrides Message Logging

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1555)

# Test Checklist

- [X] Exhibits Clear Code Structure:
- [X] Project Unit Tests Passed:
- [x] Project Integration Tests Passed:
- [x] Executes Expected Functionality:
- [ ] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Comment by JorWo** [comment]
Just making sure, will this PR also include showing the environment in the error emails?

**Comment by Kristyn-Mimura** [comment]
I'm so sorry, I linked to the wrong ticket

**Review by mhodgesatuh — APPROVED** [review]

**Review by JorWo — APPROVED** [review]
Looks good!

**Comment by fduckart** [comment]
Thank you!!!

**Pull request merged**
