### PR TITLE
Test files need to be thoroughly checked (de-spaghettify)

### PR DESCRIPTION
**Pull request by zakgilbert**
**Commits** *(squashed)*
- Organize *MembershipService.java* and *MembershipServiceImpl.java*.
- Comment out test file.
- Implement ***TestMembershipService.java*** using *@BeforeAll* annotation.
- Fix regression in ***MembershipService***.*getMembershipResult()*.
- Cover *getMembershipResults()*.
- Update ***TestMembershipService.java*** to *JUnit 5*.
- Refactor global variable *String [] username;* to *List<String> TEST_USERNAMES;*.
- Cover *addGroupMembers()*.
- Test for null uh username returned.
- Cover add portion of addInlcudeMembersTest().
- Filter out inBasis and non-currentUser related memberships to ensure a more specific test environment.
- Cover a portion of *addGroupMember()* that deals with a uh number instead of uh username.
- Jan 24th, 4:30pm - Rebased branch
- Rename *assignOwnership()* to *addOwnerships()*.
- Cover exception handling portion of *addIncludeMembers()*.
- Cover *addExcludeMembers()*.
- Cover exception portion of *removeGroupMembers()*.
- Add exception coverage to *addIncludeMembers()* and *addExcludeMembers()*.
- Cover *addOwnerships()*.
- Cover *removeOwnerships()*.
- Simplify @BeforeEach *init()* function."
- Cover *optIn()*.
- Remove supject identifier from add and remove.
- Cover *optIn()*.
- Cover *optOut()*.
- Create GROUPINGS-1020
- Create GROUPINGS-1021
- Re-implement *resetGroup()*.
- Cover *resetGroup()*.
- Re-implement *removeFromGroups()*.
- Cover *removeFromGroups()*.
- Cover *addAdmin()*.
- Cover *removeAdmin()*.
- Cover *getNumberOfMemberships()*.
- Cover *isUhUuid()*.
- Cover ***MemberAttributeService.java*** with integrations.
- Clean up ***GroupingAssignmentService.java***.
- Cover ***GroupingAssignmentService.java***.
- Clean up ***GroupAttributeService.java***.
- Cover ***GroupAttributeService.java***.
- Clean up ***HelperService.java***.
- Cover ***HelperService.java***.
- Remove *BatchDeleter* stuff.
- Clean up ***GroupingsRestControllerv2_1.java***.
- Cover ***GroupingsRestControllerv2_1.java*** itegrations.
- Create ***GrouperApiService.java***.
- Remove ***GrouperFactoryService.java*** injections and function calls. Replace with ***GrouperApiService.java***.
- Migrate ***UpdateTimestampResult.java*** to junit5.
- Rename rest of GrouperApiService functions.There were a lot of functions to rename and refactor below are some of the major ones. Mainly all the 'wsGet/Make' stuff was removed from the beginning of the functions.
    - Rename ***getWsDeleteMemberResults*** to ***removeMember***.
        - Change return type to ***DeleteMemberResult***.
    - Rename ***getWsAddMemberResults*** to ***addMember***.
        - Change return type to ***AddMemberResult***.
    - Rename ***getWsSubjectId*** to ***subjectId***.
    - Rename ***makeWsStemLookup*** to ***stemLookup***.
    - Rename ***makeWsAssignAttributeValue*** to **assignAttributeValue***.
- Continue integrations coverage for ***GrouperApiService.java***.
- Remove unused family of functions.
- Finish coverage of ***GrouperApiService.java***.
    - This needs to be put on the backburner for the moment. Going to start creating ApiReturn objects which will construct by taking in grouper object and parsing it. This will affect the coverage of ***GrouperApiService.java*** thus it needs to be waited on.
- Update ***AddMemberResult.java*** to construct using the ws grouper objects.
- Update ***RemoveMemberResult.java*** to construct using the ws grouper objects.
- Update ***MembershipService.****removeOwnerships()* to use new ***RemoveMemberResult.java*** constructor.
- Adjust ownerships tests to suit new ***AddMemberResult*** and ***RemoveMemberResult*** constructors being used.
- Add print function to JsonUtil.
- Write integrations for ***AddMemberResult.java***.
    - Touch ***TestAddMemberResult.java***.
- Write integrations for ***RemoveMemberResult.java***.
    - Touch ***TestRemoveMemberResult.java***.
- Remove ***swaggerToString()***.
- Revert back to returning complete grouper objects.
- Remove ***isOptIn/Out()***: functions were not used.
- Migrate files to junit-5.
- Port *optInGroupingsPaths()* from dev-2-2-0.
- Port *optOutGroupingsPaths()* from dev-2-2-0.
- Port *optableGroupings()* from dev-2-2-0.
- Port *allGroupingsPaths()* from dev-2-2-0.
- Template all test functions for ***GrouperApiService.java***.
- Fix *optableGroupings()* to not return optable+trio groups.
- Organize and cover ***GroupingsRestControllerv2_1Test.java***.
- Clean up
- Remove empty unit test files.
- Add uh number coverage to *addGroupMembers()*.
- Add uh number and uh username coverage to *removeGroupMembers()*.
- Add todo for enable/disbale preferences.
- Remove enable/disable prefrences test that is sending error controller advice.
- Fix JsonUtil class, constructor was not private.
---
- [x] Unit Tests
    - Tests run: 202, Failures: 0, Errors: 0, Skipped: 1
- [x] Integrations Tests
    - Tests run: 96, Failures: 0, Errors: 0, Skipped: 0

[GROUPINGS-505](https://www.hawaii.edu/jira/browse/GROUPINGS-505)

### CODE REVIEW

**Comment by zakgilbert** [comment]
Every Todo was placed on purpose, they will be removed and converted to Jira tickets once this is pushed.

**Comment by Kobeyarai808** [comment]
Codacy seems to not like this. 55 errors were found. I did not look at the entire change log but from what I saw, nothing sticks out. This pr gets my approval given we get consensus.

**Review by mhodgesatuh — COMMENTED** [review]
I can live with the Codacy issues, but are some of them easily dealt with such that they can be addressed with minimal effort?

**Comment by zakgilbert** [comment]
Should have most of the codacy issues cleared up before the meeting.

**Comment by zakgilbert** [comment]
Writing tickets for the rest of the Codacy functions as well as some other ones.

**Pull request merged**
