### PR TITLE
Fix users in exclude list can add themselves to grouping when "allow add" is unchecked

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1157](https://www.hawaii.edu/jira/browse/GROUPINGS-1157)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by fduckart** [comment]
It'd be cool if the commit message used regular English punctuation, etc.

**Comment by fduckart** [comment]
What does the JsonUtil.printJson call do, btw?

**Comment by devgav** [comment]
> What does the JsonUtil.printJson call do, btw?

I removed it forgot i left it in there was trying to check what paths were being created

**Comment by fduckart** [comment]
Okay, good, you took out that JsonUtil.printJson call.

**Comment by devgav** [comment]
> It'd be cool if the commit message used regular English punctuation, etc.

reworded the commit message

**Pull request merged**
