### PR TITLE
Removed Swagger2Markup and Asciidoctor related artifacts on dev-2-2

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[Groupings-1220](https://uhawaii.atlassian.net/browse/GROUPINGS-1220)

# List of squashed commits

- Removed Swagger2MarkupTest.java
- Removed src/docs folder that held html and pdf files from Swager2markup and Asciidoctor
- Updated Guava dependency to 30.0-jre to fix security vulnerability found by Synk

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
I believe that this is the fix for 2-2-0 that is causing trouble when deploying. I can't say whether these will actually resolve those issues but removing these unnecessary dependencies is a good first step. If anyone knows of a way to test that these changes work without having to merge that would be ideal.

**Comment by mhodgesatuh** [comment]
I can test on the Text environment.  I'm expecting that the offending mail jar will be gone.  That is easily confirmed.  Working on this now.

**Review by mhodgesatuh — APPROVED** [review]
okay to merge, and then I will test in the Test environment.

**Review by devgav — APPROVED** [review]

**Comment by mhodgesatuh** [comment]
So far so good.  API dev-2-2-0 branch redeployed to the test environment and the app still runs (no surprise there).  More to the point, the mail jar swagger invoked is no longer in the build:
`[myiamd@iws71 ~]$ !165
ls -al tomcat/webapps/uhgroupingsapi/WEB-INF/lib |grep mail
-rw-r-----. 1 myiamd myiam  670100 Aug 18  2020 jakarta.mail-1.6.5.jar
-rw-r-----. 1 myiamd myiam    4761 Sep 24  2020 spring-boot-starter-mail-2.3.1.RELEASE.jar`

**Pull request merged**
