### PR TITLE
Implement API to adhere to 'act-as' requirements.

### PR DESCRIPTION
**Pull request by hokwaichan**
# Ticket Link

[GROUPINGS-1458](https://uhawaii.atlassian.net/browse/GROUPINGS-1458)

# List of squashed commits

- rename assignOwner to setOwner and ownerUsername to ownerUhIdentifier

# Test Checklist

- [x] Unit Tests Passed:
- [x] Integration Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Why does removeMembers specify assignOwner, but assignAttributesResults specify setOwner.  What is conveyed by the two being different?  assignGrouperPrivilegesResult is in scope for this question too.

ownerUsername is no longer appropriate since we no longer use “username”. I suspect ownerUid is what is intended here.

Is currentUser meant to be the currentUserUid?  Not sure if it is that or the currentUserUhUuid.

**Comment by JorWo** [comment]
> Why does removeMembers specify assignOwner, but assignAttributesResults specify setOwner. What is conveyed by the two being different? assignGrouperPrivilegesResult is in scope for this question too.
> 
> ownerUsername is no longer appropriate since we no longer use “username”. I suspect ownerUid is what is intended here.
> 
> Is currentUser meant to be the currentUserUid? Not sure if it is that or the currentUserUhUuid.

currentUser is for uhIdentifiers, but currentUser is currently being used in a 100+ places according to my IntelliJ. A ticket should probably be created to address that rather than in this PR.

**Comment by mhodgesatuh** [comment]
if currentUser is equivalent to currentUserUhIdentifier, I think we can
live with just currentUser since the latter seems excessive.

**Comment by hokwaichan** [comment]
> 

Changed name assignOwner to setOwner and  ownerUserName to ownerUhIdentifier

**Comment by JorWo** [comment]
We will need to make sure Admins still have privileges and update the tests for Command classes that have this newly implement "setOwner" function.

**Review by JorWo — APPROVED** [review]

**Comment by JorWo** [comment]
I was looking through `GrouperApiService` and came across other methods using `.assignOwner()`. I think we should change all `setOwner` method names to `assignOwner` because the assignOwner/setOwner methods wrap `.assignActAsSubject(subjectLookup(uhIdentifier))`.

**Comment by mhodgesatuh** [comment]
sounds like a good cleanup strategy

**Comment by fduckart** [comment]
I'm a little confused why we need the "assign" part for the setter names, to be honest. Think we should just use "owner". Same thing for "assignActAsSubject".

**Pull request merged**
