### PR TITLE
Adding opencsv v5.0 dependencies

### PR DESCRIPTION
**Pull request by ruizaj**

### CODE REVIEW

**Comment by fduckart** [comment]
I don't get it. Just a pom update? Is/was this part of another commit?

**Comment by ruizaj** [comment]
It was a task for ticket 896. Just a small pom commit.

**Comment by fduckart** [comment]
I guess I'm just confused by the web interface of github or something. All I see is the addition of 5.0 opencsv, but I don't see the removal of the old duplicate dependency? That's what I don't get.

**Comment by mhodgesatuh** [comment]
For the master branch the 3.5 entry needs to be removed.  Andre explains the 2.1.1 branch there are no opencvs entries at all, so it is being added for the first time.

**Comment by fduckart** [comment]
Thanks, I get it now.

**Comment by fduckart** [comment]
Was thinking about this while running around Diamond Head... this update just can't be right.

**Pull request merged**
