### PR TITLE
Fixes bug in numberOfMemberships

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[GROUPINGS-1269](https://uhawaii.atlassian.net/browse/GROUPINGS-1269)

# List of squashed commits
- Fixes bug in numberOfMemberships

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Looks good.  Can we have this merged before my 5pm dry run this afternoon?

**Review by devgav — APPROVED** [review]
The changes look simple enough. 👍

**Comment by Kristyn-Mimura** [comment]
Hi.

Can you explain this this email?

**Comment by Kristyn-Mimura** [comment]
Please disregard last question that was emailed.

**Pull request merged**
