### PR TITLE
Removes unnecessary service interfaces

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-1252](https://uhawaii.atlassian.net/browse/GROUPINGS-1252)

# List of squashed commits

- Removes unnecessary service interfaces
- Fixes two codacy issues
- Creates helper methods for membershipResults to fix codacy issue

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
codacy reports 3 issues, 2 of which seem easily remediated

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Comment by devgav** [comment]
Looks like there are some merge conflicts that need to be resolved for this pr.

**Comment by KaileeHung** [comment]
Closing this to fix merge conflicts on another branch

**Pull request closed without merging**
