### PR TITLE
Cleaned up membershipResults

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1298)

In conjunction with https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/689

# List of squashed commits

- Made small changes

# Test Checklist

- [X] Unit Tests Passed:
- [X] Integration Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Comment by JorWo** [comment]
Not sure if I like /filtered-groupings in the URI of the membershipResults endpoint. Maybe for membershipResults it can be `/v2.1/members/{uhIdentifier}/groupings/memberships` and for managePersonResults it can be `/v2.1/members/{uhIdentifier}/groupings/all`.

**Comment by mhodgesatuh** [comment]
We don't have a good name for the expression of basis+include-exclude,
unfortunately, especially given that the expression is the very reason that
the grouping exists in the first place.  Since this expression is how we
derive membership, it does stand to reason that the following would be
appropriate:
 o /v2.1/members/{uhIdentifier}/groupings/memberships
If you read the description of the new entry on the RESTful API page it too
calls out "memberships".

I'm not sure the "all" reference is needed.

**Review by JorWo — APPROVED** [review]
Thanks for making the changes to the API URIs.

**Pull request merged**
