### PR TITLE
/admin - can't remove an admin with no UH Username

### PR DESCRIPTION
**Pull request by zakgilbert**
***COMMITS***
- Refactor MemberAttributeServiceImpl#getMemberAttributes.
- Update integrations *memberAttributesTest()*.
- Add missing setters to Person class.
- Remove '_' from test function names.
- Move *SubjectsResults.java* from **Service** to **Type** directory.
- Move *SubjectsResultsTest.java* from **Service** to **Type** directory.
- Cover *firstName* and *lastName* accessors in **Person.java**.
---
[GROUPINGS-1131](https://www.hawaii.edu/jira/browse/GROUPINGS-1131)
- [x] Unit
- [x] Integrations
- [x] Visual Inspection

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
and now I see where Frank's Thursday conversation came from

**Comment by fduckart** [comment]
Why do we need the person setters?

**Comment by zakgilbert** [comment]
> Why do we need the person setters?

Not having them was breaking some of the integration tests in TestGroupingRestControllerv2_1.java.

**Comment by fduckart** [comment]
Hmm, I see what you mean about the Person setters in the integration test. I wonder if it's just the tests that need them or whether our app uses them, too? Can you add some tests to the straight unit side that uses the setters?

**Pull request merged**
